package com.tungnv.entity;

public class Car_Info {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.idcar_info
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    private Integer idcarInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.car_number
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    private String carNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.type
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_info.weight
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    private String weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.idcar_info
     *
     * @return the value of car_info.idcar_info
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public Integer getIdcarInfo() {
        return idcarInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.idcar_info
     *
     * @param idcarInfo the value for car_info.idcar_info
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public void setIdcarInfo(Integer idcarInfo) {
        this.idcarInfo = idcarInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.car_number
     *
     * @return the value of car_info.car_number
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.car_number
     *
     * @param carNumber the value for car_info.car_number
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber == null ? null : carNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.type
     *
     * @return the value of car_info.type
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.type
     *
     * @param type the value for car_info.type
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_info.weight
     *
     * @return the value of car_info.weight
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_info.weight
     *
     * @param weight the value for car_info.weight
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }
}