package com.tungnv.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.iduser
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    private Integer iduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.del_flg
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    private Boolean delFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.iduser
     *
     * @return the value of user.iduser
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.iduser
     *
     * @param iduser the value for user.iduser
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.del_flg
     *
     * @return the value of user.del_flg
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.del_flg
     *
     * @param delFlg the value for user.del_flg
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }
}