package com.tungnv.dao;

import com.tungnv.entity.Car_Info;

public interface Car_InfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_info
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    int deleteByPrimaryKey(Integer idcarInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_info
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    int insert(Car_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_info
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    int insertSelective(Car_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_info
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    Car_Info selectByPrimaryKey(Integer idcarInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_info
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    int updateByPrimaryKeySelective(Car_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_info
     *
     * @mbg.generated Sat Oct 29 11:10:00 ICT 2016
     */
    int updateByPrimaryKey(Car_Info record);
}